services:
  - type: web
    name: employee-support-portal
    env: static
    buildCommand: npm run build
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /*
        name: Permissions-Policy
        value: camera=(), microphone=(), geolocation=()
    envVars:
      - key: SUPABASE_URL
        value: https://your-project.supabase.co
      - key: SUPABASE_ANON_KEY
        value: your-anon-key-here
      - key: APP_NAME
        value: Employee Support Portal
      - key: APP_VERSION
        value: 1.0.0
      - key: NODE_ENV
        value: production
